{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: climon-operator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
  name: climon-operator-rolebinding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: climon-operator-role-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: '{{ .Values.serviceAccount.name }}'
  namespace: '{{ .Release.Namespace }}'
{{- end }}