{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: climon-operator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
  name: '{{ .Values.serviceAccount.name }}'
  namespace: '{{ .Release.Namespace }}'
{{- end }}