# permissions for end users to edit monitoringconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoringconfiguration-editor-role
rules:
- apiGroups:
  - monitoring.soi.dev
  resources:
  - monitoringconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.soi.dev
  resources:
  - monitoringconfigurations/status
  verbs:
  - get
