# permissions for end users to view monitoringconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoringconfiguration-viewer-role
rules:
- apiGroups:
  - monitoring.soi.dev
  resources:
  - monitoringconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.soi.dev
  resources:
  - monitoringconfigurations/status
  verbs:
  - get
