# permissions for end users to view prometheusdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheusdeployment-viewer-role
rules:
- apiGroups:
  - monitoring.climon.com
  resources:
  - prometheusdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.climon.com
  resources:
  - prometheusdeployments/status
  verbs:
  - get
